name: Release

on:
  release:
    types: [published]

jobs:
  release_zip_file:
    name: Prepare release asset
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      # Pack the open_meteo_solar_forecast dir as a zip and upload to the release
      - name: ZIP adventurous-solar-forecast Dir
        run: |
          cd ${{ github.workspace }}/custom_components/adventurous-solar-forecast
          zip adventurous-solar-forecast.zip -r ./
      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ github.workspace }}/custom_components/adventurous_solar_forecast/adventurous-solar-forecast.zip
          asset_name: adventurous-solar-forecast.zip
          tag: ${{ github.ref }}
          overwrite: true
